services:
  masternode:
    build: ./master/
    hostname: sparkmaster
    image: spark-master
    cpus: 2
    mem_limit: 2G
    ports:
      - "8080:8080"
    expose:
      - "7077"
    networks:
      - spark-cluster
  workernode:
    build: ./worker/
    image: sparkworker_03_20
    cpus: 2
    mem_limit: 2G
    ports:
      - "8081-8088:8080"
    depends_on:
      - masternode
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
    networks:
      - spark-cluster
  jupyternode:
    build: ./jupyter-setup/
    hostname: jupyter
    image: jupyter_03_20 #jupyter-node
    cpus: 3
    mem_limit: 3G
    ports:
      - "8888-8900:8888"
    networks:
      - spark-cluster

networks:
  spark-cluster:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
